package br.com.capoeiramundial.config;
import br.com.capoeiramundial.entity.*; import br.com.capoeiramundial.repository.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.CommandLineRunner; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Component; import java.time.*;
@Component public class DataSeeder implements CommandLineRunner {
 private final AdminUserRepository admins; private final EventRepository events; private final MemberRepository members; private final TrainingScheduleRepository trainings; private final SiteContentRepository contents; private final PasswordEncoder encoder;
 @Value("${app.admin.username}") String username; @Value("${app.admin.password}") String password;
 public DataSeeder(AdminUserRepository a,EventRepository e,MemberRepository m,TrainingScheduleRepository t,SiteContentRepository c,PasswordEncoder p){admins=a;events=e;members=m;trainings=t;contents=c;encoder=p;}
 public void run(String...x){if(admins.count()==0)admins.save(new AdminUser(username,encoder.encode(password))); if(contents.count()==0){contents.save(new SiteContent("home_intro","Criado em 2019 por Marcos Ribeiro, o Mestre Chumbim, o Grupo Capoeira Mundial transforma disciplina em futuro. Aqui, cada ginga aproxima jovens do esporte, da cultura e de novas possibilidades.","Apresentacao da Home"));contents.save(new SiteContent("about_history","A nossa roda nasceu do desejo de manter viva a capoeira e abrir caminhos para uma nova geracao.","Historia"));} ensureContent("home_hero_image","https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=2000&q=88","Imagem principal da Home");ensureContent("home_founder_image","https://images.unsplash.com/photo-1539627831859-a911cf04d3cd?auto=format&fit=crop&w=1200&q=85","Imagem do Mestre na Home");ensureContent("home_graduation_image","","Banner da ordem de graduacao na Home");ensureContent("home_cta_image","https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=85","Imagem final da Home");
 if(trainings.count()==0){TrainingSchedule t=new TrainingSchedule();t.setWeekday("Terças e quintas");t.setStartTime(LocalTime.of(19,0));t.setEndTime(LocalTime.of(21,0));t.setVenue("Centro Comunitário");t.setCityState("São Paulo/SP");t.setNotes("Primeira aula gratuita");trainings.save(t);} if(members.count()==0){Member m=new Member();m.setName("Marcos Ribeiro");m.setNickname("Mestre Chumbim");m.setGraduation("Mestre");m.setRole("Fundador e Mestre");m.setBiography("Fundador do Grupo Capoeira Mundial e educador dedicado à transformação pela cultura e pelo esporte.");members.save(m);} }
 private void ensureContent(String key,String value,String label){if(contents.findByContentKey(key).isEmpty())contents.save(new SiteContent(key,value,label));}
}
