package br.com.capoeiramundial.controller;
import br.com.capoeiramundial.entity.*; import br.com.capoeiramundial.repository.*; import br.com.capoeiramundial.service.StorageService; import jakarta.validation.Valid; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.mvc.support.RedirectAttributes; import java.io.IOException;
@Controller @RequestMapping("/admin") public class AdminController {
 private final EventRepository events; private final MemberRepository members; private final VideoRepository videos; private final TrainingScheduleRepository trainings; private final GalleryImageRepository gallery; private final SiteContentRepository contents; private final ContactInfoRepository contacts; private final StorageService storage;
 public AdminController(EventRepository e,MemberRepository m,VideoRepository v,TrainingScheduleRepository t,GalleryImageRepository g,SiteContentRepository s,ContactInfoRepository c,StorageService st){events=e;members=m;videos=v;trainings=t;gallery=g;contents=s;contacts=c;storage=st;}
 @GetMapping String dashboard(Model m){m.addAttribute("events",events.count());m.addAttribute("members",members.count());m.addAttribute("videos",videos.count());m.addAttribute("trainings",trainings.count());return "admin/dashboard";}
 @GetMapping("/eventos") String events(Model m){m.addAttribute("items",events.findAllByOrderByEventDateAsc());m.addAttribute("section","eventos");return "admin/list";} @GetMapping("/eventos/novo") String newEvent(Model m){m.addAttribute("item",new Event());return form(m,"evento");} @GetMapping("/eventos/{id}") String editEvent(@PathVariable Long id,Model m){m.addAttribute("item",events.findById(id).orElseThrow());return form(m,"evento");}
 @PostMapping("/eventos") String saveEvent(@Valid @ModelAttribute("item") Event item,BindingResult br,@RequestParam(required=false) MultipartFile image,Model m,RedirectAttributes ra)throws IOException{if(br.hasErrors())return form(m,"evento");String previous=item.getId()==null?null:events.findById(item.getId()).map(Event::getImageUrl).orElse(null);String url=storage.store(image,false);item.setImageUrl(url!=null?url:previous);events.save(item);return saved(ra,"eventos");} @PostMapping("/eventos/{id}/excluir") String delEvent(@PathVariable Long id){events.deleteById(id);return "redirect:/admin/eventos";}
 @GetMapping("/integrantes") String members(Model m){m.addAttribute("items",members.findAllByOrderByDisplayOrderAscNameAsc());m.addAttribute("section","integrantes");return "admin/list";} @GetMapping("/integrantes/novo") String newMember(Model m){m.addAttribute("item",new Member());return form(m,"integrante");} @GetMapping("/integrantes/{id}") String editMember(@PathVariable Long id,Model m){m.addAttribute("item",members.findById(id).orElseThrow());return form(m,"integrante");}
 @PostMapping("/integrantes") String saveMember(@Valid @ModelAttribute("item") Member item,BindingResult br,@RequestParam(required=false) MultipartFile image,Model m,RedirectAttributes ra)throws IOException{if(br.hasErrors())return form(m,"integrante");String previous=item.getId()==null?null:members.findById(item.getId()).map(Member::getPhotoUrl).orElse(null);String url=storage.store(image,false);item.setPhotoUrl(url!=null?url:previous);members.save(item);return saved(ra,"integrantes");} @PostMapping("/integrantes/{id}/excluir") String delMember(@PathVariable Long id){members.deleteById(id);return "redirect:/admin/integrantes";}
 @GetMapping("/videos") String videos(Model m){m.addAttribute("items",videos.findAllByOrderByPublishedAtDesc());m.addAttribute("section","videos");return "admin/list";} @GetMapping("/videos/novo") String newVideo(Model m){m.addAttribute("item",new Video());return form(m,"video");} @GetMapping("/videos/{id}") String editVideo(@PathVariable Long id,Model m){m.addAttribute("item",videos.findById(id).orElseThrow());return form(m,"video");}
 @PostMapping("/videos") String saveVideo(@Valid @ModelAttribute("item") Video item,BindingResult br,@RequestParam(required=false) MultipartFile media,@RequestParam(required=false) MultipartFile image,Model m,RedirectAttributes ra)throws IOException{if(br.hasErrors())return form(m,"video");Video previous=item.getId()==null?null:videos.findById(item.getId()).orElse(null);String f=storage.store(media,true),thumb=storage.store(image,false);item.setFileUrl(f!=null?f:previous==null?null:previous.getFileUrl());item.setThumbnailUrl(thumb!=null?thumb:previous==null?null:previous.getThumbnailUrl());videos.save(item);return saved(ra,"videos");} @PostMapping("/videos/{id}/excluir") String delVideo(@PathVariable Long id){videos.deleteById(id);return "redirect:/admin/videos";}
 @GetMapping("/agenda") String trainings(Model m){m.addAttribute("items",trainings.findAll());m.addAttribute("section","agenda");return "admin/list";} @GetMapping("/agenda/novo") String newTraining(Model m){m.addAttribute("item",new TrainingSchedule());return form(m,"treino");} @GetMapping("/agenda/{id}") String editTraining(@PathVariable Long id,Model m){m.addAttribute("item",trainings.findById(id).orElseThrow());return form(m,"treino");}
 @PostMapping("/agenda") String saveTraining(@Valid @ModelAttribute("item") TrainingSchedule item,BindingResult br,Model m,RedirectAttributes ra){if(br.hasErrors())return form(m,"treino");trainings.save(item);return saved(ra,"agenda");} @PostMapping("/agenda/{id}/excluir") String delTraining(@PathVariable Long id){trainings.deleteById(id);return "redirect:/admin/agenda";}
 @GetMapping("/galeria") String gallery(Model m){m.addAttribute("items",gallery.findAllByOrderByDisplayOrderAsc());m.addAttribute("section","galeria");return "admin/list";} @GetMapping("/galeria/novo") String newGallery(Model m){m.addAttribute("item",new GalleryImage());return form(m,"galeria");} @PostMapping("/galeria") String saveGallery(@ModelAttribute GalleryImage item,@RequestParam MultipartFile image,RedirectAttributes ra)throws IOException{String url=storage.store(image,false);if(url!=null)item.setImageUrl(url);gallery.save(item);return saved(ra,"galeria");} @PostMapping("/galeria/{id}/excluir") String delGallery(@PathVariable Long id){gallery.deleteById(id);return "redirect:/admin/galeria";}
 @GetMapping("/conteudo") String content(Model m){m.addAttribute("items",contents.findAll());m.addAttribute("section","conteudo");return "admin/list";} @GetMapping("/conteudo/{id}") String editContent(@PathVariable Long id,Model m){m.addAttribute("item",contents.findById(id).orElseThrow());return form(m,"conteudo");} @PostMapping("/conteudo") String saveContent(@Valid @ModelAttribute SiteContent item,@RequestParam(required=false) MultipartFile image,RedirectAttributes ra)throws IOException{String url=storage.store(image,false);if(url!=null)item.setContentValue(url);contents.save(item);return saved(ra,"conteudo");}
 @GetMapping("/contatos") String contacts(Model m){m.addAttribute("items",contacts.findAll());m.addAttribute("section","contatos");return "admin/list";} @GetMapping("/contatos/novo") String newContact(Model m){m.addAttribute("item",new ContactInfo());return form(m,"contato");} @GetMapping("/contatos/{id}") String editContact(@PathVariable Long id,Model m){m.addAttribute("item",contacts.findById(id).orElseThrow());return form(m,"contato");} @PostMapping("/contatos") String saveContact(@Valid @ModelAttribute ContactInfo item,RedirectAttributes ra){contacts.save(item);return saved(ra,"contatos");} @PostMapping("/contatos/{id}/excluir") String delContact(@PathVariable Long id){contacts.deleteById(id);return "redirect:/admin/contatos";}
 private String form(Model m,String type){m.addAttribute("type",type);return "admin/form";} private String saved(RedirectAttributes ra,String route){ra.addFlashAttribute("success","Alterações salvas com sucesso.");return "redirect:/admin/"+route;}
}
